//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public long id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string modelNumber { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> depth { get; set; }
        public string description { get; set; }
        public Nullable<int> category { get; set; }
    }
}
