//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public string address { get; set; }
        public string stagerName { get; set; }
        public string stagerCell { get; set; }
        public string term { get; set; }
        public string agentName { get; set; }
        public string agentCell { get; set; }
        public string sellerName { get; set; }
        public string sellerCell { get; set; }
        public string payfee { get; set; }
        public string lockbox { get; set; }
        public string orderInvoice { get; set; }
        public Nullable<System.DateTime> stageDate { get; set; }
        public Nullable<System.DateTime> pickupDate { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<double> fee { get; set; }
        public Nullable<double> orderProcessing { get; set; }
        public Nullable<double> delivery { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> orderType { get; set; }
        public bool bidFlag { get; set; }
    }
}
